### ISSUE TITLE
Missing `RequireAnonymousLinksExpireInDays`, `DisallowInfectedFileDownload` in `tenantAdmin.settings` response

### ISSUE THREAD

**Issue by Subhajit97** [microsoftgraph/msgraph-beta-sdk-go#146]
Hi, I'm trying to get the tenant-level settings for SharePoint.
But in the response, I didn't see any method defined to get the value for `RequireAnonymousLinksExpireInDays` and `DisallowInfectedFileDownload`.

API reference: https://docs.microsoft.com/en-us/graph/api/resources/tenantadmin-settings?view=graph-rest-beta
https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/d367f894814f3f568a5126ecb35763faf8bb5aab/models/tenantadmin/settingsable.go#L9

**Comment by rkodev** [comment]
Hi @Subhajit97
This property is not currently supported by the SDK hence the reason its not listed in documentation.

**Comment by Subhajit97** [comment]
Thanks, @rkodev, for confirming. Is there any timeline for adding these properties?
Is there any workaround I can try out?

**Comment by baywet** [comment]
Hi @Subhajit97,
This repository (and associated issues) is dedicated to the Go SDK itself.
For questions about the APIs, please [reach out on the dedicated Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-files.html), you'll get replies from the service team this way.
Closing.
