### ISSUE TITLE
Unable to get member groups of an Administrative Unit

### ISSUE THREAD

**Issue by ihulsbus** [microsoftgraph/msgraph-beta-sdk-go#156]
Hi, I'm trying to retrieve the member groups of an administrative unit but for some reason I can't figure out how to construct the call. 
my current attempt: 
```go
query := client.AdministrativeUnitsById("<omit>").GetMemberGroups()
```
query is of the type `*getmembergroups.GetMemberGroupsRequestBuilder` but that's where I get stuck. I get that I need to pass this to a get() of the MemberGroups object, but something like that does not exist it seems.  I also tried the `Get()` in `AdministrativeUnitsById()` and `AdministrativeUnits()` but they don't accept the given type. 

Am I missing something obvious here or is the SDK missing functions? 

Thanks

**Comment by baywet** [comment]
Hi @ihulsbus 
Thanks for using the Go SDK and for reaching out.

First off, you should only be using the beta SDK (which maps to the beta version of the API) for APIs that are not available in v1. 
This API is available in V1 and we strongly recommend you use the v1 SDK instead.

As for the query, [the documentation](https://learn.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-1.0&tabs=go) contains snippets to help you build your request. But if you want all members of an administrative unit, this snippet should help you get that.

```go
result, err := graphClient.Directory().AdministrativeUnitsById("administrativeUnit-id").Members().Get(context.Background(), nil)
```

If you want just the members that are groups, you can even use this snippet instead.

```go
result, err := graphClient.Directory().AdministrativeUnitsById("administrativeUnit-id").Members().Group().Get(context.Background(), nil)
```

let us know if you need anything else.

**Comment by ihulsbus** [comment]
Hi @baywet
Thanks for the snippets and the clue in the non-beta sdk! for some reason I did not find the AU part in `Directory()`IT resolved the issue. 

Cheers,
