### ISSUE TITLE
`/tenantRelationships/managedTenants/tenants` fails with an error `Request not applicable to target tenant.`

### ISSUE THREAD

**Issue by Subhajit97** [microsoftgraph/msgraph-beta-sdk-go#198]
Hi! I am trying to get a list of the tenant objects and their properties using [List Tenants](https://learn.microsoft.com/en-us/graph/api/managedtenants-managedtenant-list-tenants?view=graph-rest-beta&tabs=http) API. But the request fails with an error `BadRequest`.

```
"error": {
        "code": "BadRequest",
        "message": "Request not applicable to target tenant.",
        "innerError": { ... }
    }
```
Should I include something here, or is it an issue in the above API?

I was going through the below discussion https://learn.microsoft.com/en-us/answers/questions/1063413/error-graph-api.html, where it mentioned it requires an active Intune license.
Do we always require an Active Intune license to access this API, or is there any workaround?

**Comment by baywet** [comment]
Hi @Subhajit97 
Thanks for using the Go SDK and for reaching out.
This repo and associated issues are dedicated to the SDK itself (API surface, issues with the requests being built, serialization, etc...) service owners do not watch it.
The best thing to do is to post in the dedicated Microsoft Q&A forums where members of the service teams are providing answers. As you've already linked to an existing question, I'd encourage you to add a comment to ask for clarifications.
