### ISSUE TITLE
SharePoint: Site Permissions

### ISSUE THREAD

**Issue by dadams39** [microsoftgraph/msgraph-beta-sdk-go#200]
@baywet , I was unable to find any documentation on using the Graph API to upload documents to some of the restricted folders such as `sharepoint.com/_catalogs/masterpage/Forms` directory. Would the use of the [Permissions API](https://learn.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-beta) for the Azure application that we run Graph API enable the use of the regular upload via [Drive Item API](https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http) into these directories or is there another call that will be rolling out to enable the update to directories  like `sharepoint.com/_catalogs/themes/` ?

Apologies, I did not see a discussion forum.

**Comment by baywet** [comment]
@dadams39 please refrain from mentioning people when you create issues. We do have a triage process, sometimes I'm going to be doing the triage, sometimes it'll be somebody else from the team and it creates unnecessary noise.
As per the question, as you know this repo is dedicated to the SDK itself. The forum [is the following one](https://learn.microsoft.com/en-us/answers/topics/microsoft-graph-files.html) so you can get an answer from API owners.
