### ISSUE TITLE
Site Builders Not checking for potential errors 

### ISSUE THREAD

**Issue by dadams39** [microsoftgraph/msgraph-beta-sdk-go#212]
Within the `Sites` directory, many of the request builders, use `SetContentFromParsable`, an [example](https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/838bb877cd7d1950c26c49caf697f5e27e51119e/sites/site_item_request_builder.go#L307). 

As of `kiota-abstractions-go v0.16.0`, this function can potentially return an error.

**Comment by baywet** [comment]
Hi @dadams39,
Thanks for calling this generation bug out, schedule it for fixing.
@rkodev in the generation we need to assign the return to a variable and return the error if we get one.
