### ISSUE TITLE
How can i create a client with AccessToken

### ISSUE THREAD

**Issue by shachardevops** [microsoftgraph/msgraph-beta-sdk-go#227]
```golang
        //import msgraphsdkgo  github.com/microsoftgraph/msgraph-sdk-go
	//...
	//...
	l := azcore.TokenCredential{Token: oauthToken.AccessToken}
	// cred, err := azidentity.NewChainedTokenCredential(l, nil)
	t := "my access token"
	graphClient := msgraphsdkgo.NewGraphServiceClient(adapter?)
	if err != nil {
		fmt.Printf("Error NewGraphServiceClient client: %v\n", err)
		return nil, err
	}
```
How can I create a client with the access token that I have? i got lost

**Comment by baywet** [comment]
Hi @shachardevops 
Thanks for reaching out and for your interest in the Go SDK.

First off, we generally discourage people from getting, storing, and passing tokens themselves. That poses a number of challenges and should only be implemented whenever the context is not suitable for the [already available authentication credentials](https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Go)

In case you still need your custom implementation, the interface you need to implement is the [Token Crendentials](https://github.com/Azure/azure-sdk-for-go/blob/7e7d2a8dcb1e0fd36ba74024b645c4348671bcf4/sdk/azcore/internal/exported/exported.go#L80) one. So:
1. Define a struct that can hold the token value
2. Have that struct implement the GetToken method
3. Create an instance of that struct
4. Get a reference to that instance
5. Pass that reference to the GraphClient constructor

You should then be able to use the client.

Let us know if you have further questions.

**Comment by shachardevops** [comment]
works, great!
Is there a way to override HTTP transport of the get request? 
```golang
	groupsBuilder := graphClient.UsersById(OID).MemberOf()
	params := &users.ItemMemberOfRequestBuilderGetRequestConfiguration{<mysettings>}
	// Get the group memberships of the user
	groupsIds, err := groupsBuilder.Get(ctx, params)
	if err != nil {
		return nil, err
	}
```

**Comment by baywet** [comment]
The client uses something called a request adapter, and the request adapter itself accepts the net http client.
We use the transport to setup a middleware layer so cross-cutting concerns like retrying transient errors can be handled globally.
So the easiest for you would probably to implement another middleware handler and add it to the ones we already provide.

A few pointers
https://github.com/microsoftgraph/msgraph-sdk-go/blob/510e28d545926da5b3fd5f038f018e0002bb6194/graph_service_client.go#L14
https://github.com/microsoftgraph/msgraph-sdk-go/blob/510e28d545926da5b3fd5f038f018e0002bb6194/graph_request_adapter.go#L64
https://github.com/microsoft/kiota-http-go/blob/c11ec006527206e4c7e4be3b096220c5b05a8433/retry_handler.go#L104
https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/d9690cc17270acb8638f36311e6a49db0dd4c99a/graph_client_factory.go#L10

**Comment by shachardevops** [comment]
I will appreciate your extra help here. I just need to find a way to override HTTP transport

**Comment by baywet** [comment]
what do you need the custom transport for?
