### ISSUE TITLE
Get ConditionalAccess Policies returns error Unknown ConditionalAccessGuestOrExternalUserTypes value: internalGuest,otherExternalUser

### ISSUE THREAD

**Issue by akshaypatel96** [microsoftgraph/msgraph-beta-sdk-go#262]
Hi Team,
When trying to get list of Conditional Access Policies, an unexpected error is encountered.

```
result, err := client.Identity().ConditionalAccess().Policies().Get(context.Background(), nil)
  if err != nil {
    return nil, err
  }
```
_Error: Unknown ConditionalAccessGuestOrExternalUserTypes value: internalGuest,otherExternalUser_

https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/838bb877cd7d1950c26c49caf697f5e27e51119e/identity/conditional_access_request_builder.go#L157

The Graph Explorer Rest API -  List ConditionalAccessPolicies GET call is returning correct data
```
"includeGuestsOrExternalUsers": {
                        "guestOrExternalUserTypes": "internalGuest,otherExternalUser",
                        "externalTenants": {
                            "@odata.type": "#microsoft.graph.conditionalAccessAllExternalTenants",
                            "membershipKind": "all"
                        }
                    }
```

https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/838bb877cd7d1950c26c49caf697f5e27e51119e/models/conditional_access_guest_or_external_user_types.go#L42

The `func ParseConditionalAccessGuestOrExternalUserTypes` at line 22 is not able to return multiples values of userTypes.

Can you kindly look into the issue and provide fix or solution.
Thank you!

Reference Screenshots:
![image](https://user-images.githubusercontent.com/30474714/230091048-01108114-12a2-449d-891a-d44721ae0f7f.png)
![image](https://user-images.githubusercontent.com/30474714/230093414-6557307c-69dc-4060-90b5-e1b721a89cb7.png)

**Comment by akshaypatel96** [comment]
@baywet @rkodev it's a bug and needed attention

**Comment by nshrikanth** [comment]
@baywet @rkodev any update on this please?

**Comment by rkodev** [comment]
Hi @akshaypatel96 , thanks for raising this bug. As you have noted, the values in the field `guestOrExternalUserTypes` is expected to be a single value of one of the enums but is currently a csv value. 

We have a similar issue reported that is currently in progress so kindly follow it on [this related issue]( https://github.com/microsoftgraph/msgraph-sdk-go/issues/517)

**Comment by akshaypatel96** [comment]
Hi @baywet, @rkodev , the fix mentioned in related issue will be applicable to msgraph-beta-sdk-go as well? In which version of beta sdk we can expect fix for this issue? 
Thanks!
