### ISSUE TITLE
Serialization of platforms not returning expected value.

### ISSUE THREAD

**Issue by ravitejareddybejawada** [microsoftgraph/msgraph-beta-sdk-go#366]
I am trying to create a Device Management Configuration Policy using Post api. In the process I am trying to set the platform to "windows10 and later" which enumerates to `WINDOWS10_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS` in the file [/msgraph-beta-sdk-go@v0.87.0/models/device_management_configuration_platforms.go](https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/main/models/device_management_configuration_platforms.go)

when I try to print the platform value, `android,windows10X` is printed instead of `windows10`.
![image (3)](https://github.com/microsoftgraph/msgraph-beta-sdk-go/assets/52754677/7e02dacc-3221-4852-af01-48478f3b8801)

Upon investigation, we identified value for `WINDOWS10_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS` is set to 5 `(const WINDOWS10_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS DeviceManagementConfigurationPlatforms = 5)` instead of 32(2**5) which would facilitate the left shift algorithm used in [String](https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/main/models/device_management_configuration_platforms.go#28-36) method. 

I think similar changes are needed wherever the left shift algorithm is used.

**Comment by baywet** [comment]
Hi @ravitejareddybejawada 

Thanks for bringing this up to our attention.

This

```Go
const (
    // Default. No platform type specified.
    NONE_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS DeviceManagementConfigurationPlatforms = iota
    // Settings for Android platform.
    ANDROID_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS
    // Settings for iOS platform.
    IOS_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS
    // Settings for MacOS platform.
    MACOS_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS
    // Windows 10 X.
    WINDOWS10X_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS
    // Settings for Windows 10 platform.
    WINDOWS10_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS
    // Settings for Linux platform.
    LINUX_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS
    // Evolvable enumeration sentinel value. Do not use.
    UNKNOWNFUTUREVALUE_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS
)
```

Should instead be generated like that

```go
const (
    // Default. No platform type specified.
    NONE_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS DeviceManagementConfigurationPlatforms = 1
    // Settings for Android platform.
    ANDROID_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 2
    // Settings for iOS platform.
    IOS_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 4
    // Settings for MacOS platform.
    MACOS_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 8
    // Windows 10 X.
    WINDOWS10X_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 16
    // Settings for Windows 10 platform.
    WINDOWS10_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 32
    // Settings for Linux platform.
    LINUX_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 64
    // Evolvable enumeration sentinel value. Do not use.
    UNKNOWNFUTUREVALUE_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 128
)
```

And this 
```go
func (i DeviceManagementConfigurationPlatforms) String() string {
    var values []string
    for p := DeviceManagementConfigurationPlatforms(1); p <= UNKNOWNFUTUREVALUE_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS; p <<= 1 {
        if i&p == p {
            values = append(values, []string{"none", "android", "iOS", "macOS", "windows10X", "windows10", "linux", "unknownFutureValue"}[p])
        }
    }
    return strings.Join(values, ",")
}
```

should instead be generated like that

```go
func (i DeviceManagementConfigurationPlatforms) String() string {
    var values []string
    for p := 0; p < 6; p++ {
        mantis := math.Pow(2, p)
        if i&mantis == mantis {
            values = append(values, []string{"none", "android", "iOS", "macOS", "windows10X", "windows10", "linux", "unknownFutureValue"}[p])
        }
    }
    return strings.Join(values, ",")
}
```

> Note: Ideally the array for the values would be declared outside of the loop so we don't pay an allocation cost on every iteration.

I'll create an issue in the generator shortly to cover this change.
