### ISSUE TITLE
unable to use gov .us tenant

### ISSUE THREAD

**Issue by ronsun8** [microsoftgraph/msgraph-beta-sdk-go#39]
### Bug Report

- ./github.com/microsoftgraph/msgraph-beta-sdk-go/graph_service_client.go  
- graph sdk ## [0.4.2] - 2021-12-07
- go version go1.16.2 darwin/amd64

I'm on a gov azure tenant and I'm unable to use `result, err := client.ServicePrincipals().Get(nil)`

I'm explicitly declaring `AuthorityHost: azidentity.AzureGovernment` but the error message says the SDK is still trying to use the public ".com" cloud instead of ".us":

```Get "https://graph.microsoft.com/beta/servicePrincipals": 302 response missing Location header```

I tested the same code against a public cloud tenant and it works great.

Here is how I'm initializing the client.
```
cred, err := azidentity.NewClientSecretCredential(
	tenantID, clientID, clientSecret, &azidentity.ClientSecretCredentialOptions{
			AuthorityHost: azidentity.AzureGovernment,
		},
	)
auth, err := azure.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{})
adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
client := msgraphsdk.NewGraphServiceClient(adapter)
```

If I add `adapter.SetBaseUrl("https://graph.microsoft.us/beta")` the 302 error goes away, but I get an empty response.

I believe the problem is `./github.com/microsoftgraph/msgraph-beta-sdk-go/graph_service_client.go`
hard coding to ".com" on L505:
```    m.requestAdapter.SetBaseUrl("https://graph.microsoft.com/beta")```

Thanks!

**Comment by baywet** [comment]
Hi @ronsun8 
Thanks for trying out the SDK and for reaching out.

First off, always set the base URL AFTER creating a new client, right now the client constructor sets the base URL. Example.

```Golang
cred, err := azidentity.NewClientSecretCredential(
	tenantID, clientID, clientSecret, &azidentity.ClientSecretCredentialOptions{
			AuthorityHost: azidentity.AzureGovernment,
		},
	)
auth, err := azure.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{})
adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
client := msgraphsdk.NewGraphServiceClient(adapter)
adapter.SetBaseUrl("https://graph.microsoft.us/beta") // this is after we created the client.
```

Second, for sanity, please run `go get -u` at the root of your project to make sure you're on the latest version of all the dependencies. Both the SDK and the authentication library are in preview, and things can be moving fast. After upgrading and setting the base URL, let us know if this happens again.

Which scopes have you set in the app registrations?

Please update the following line `azure.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{})` to `azure.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{"https://graph.microsoft.us/.default"})`

Let us know if this fixes your issue.

**Comment by ronsun8** [comment]
setting the scope did the trick!  thanks for the fast support!!
