### ISSUE TITLE
AuditLogSearchRecordsQuery Invalid Json Type

### ISSUE THREAD

**Issue by L4r1k** [microsoftgraph/msgraph-beta-sdk-go#426]
Hi, I'm receiving the following error when retrieving the records of a completed audit log search query:

`invalid json type`

I'm trying to track down exactly what records this error occurs on but the above error is all the information I have to go on for some pretty large queries. I believe this may be getting caused by invalid/corrupt JSON data being present in the audit log search records but I wanted to report it here to make you aware. Would appreciate any help you can provide here as I dig further into the issue.

The relevant graph endpoint is [here](https://learn.microsoft.com/en-us/graph/api/security-auditlogquery-list-records?view=graph-rest-beta&tabs=http)

**Comment by andrueastman** [comment]
Thanks for raising this @L4r1k 

Any chance you are in a position to confirm if the Json response is invalid Json by capturing the raw json response body in such scenarios?

**Comment by L4r1k** [comment]
Do you have any suggestions there? I am unable to see the raw data because the iterator errors out before returning it. I also can't iterate any further because the OData link for subsequent data never gets returned either.

I've been debugging for hours and managed to narrow the issue down to what appears to be a handful of problem logs in hundreds of thousands and am still working on getting the raw output. Unfortunately any values that go into any models related to the SDK just become 'unresolved interface types'

**Comment by L4r1k** [comment]
Has this been raised with the appropriate teams internally? It is a critical bug for retrieving unified audit logs via Graph

**Comment by baywet** [comment]
This error is [returned here](https://github.com/microsoft/kiota-serialization-json-go/blob/efba7ca94448556e7f6405eade0e7194f04e31ba/json_parse_node.go#L33) suggesting the response you're getting is simply invalid JSON.
At this point I suggest you log the request ID and the timestamps when this happens, and open a support ticket.
The service team is not watching this repository, and we don't have access to backend service logs for security reasons.
