### ISSUE TITLE
`AuditLogQuery.SetUserPrincipalNameFilters()` weird behavior

### ISSUE THREAD

**Issue by epigone707** [microsoftgraph/msgraph-beta-sdk-go#451]
### Describe the bug

I have some audit log records whose userprincipalname=SHAREPONT/system.
However, when I use `SetUserPrincipalNameFilters()` to set a “SHAREPONT//system” (double backslash to escape) filter, the query then returns no record.  

And I’ve checked the filter is indeed “SHAREPONT/system” using getAuditLogQueryById endpoint and  `GetUserPrincipalNameFilters()`.

Then when I set UPN filter to be "system", the query returns those records whose  UPN=“SHAREPONT/system”

Is this normal?

### Expected behavior

use `SetUserPrincipalNameFilters()` to set a “SHAREPONT/system” filter, the query should return the records.  

### How to reproduce

Has described in previous section. 

### SDK Version

0.107.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by rkodev** [comment]
Hi @epigone707, thanks for trying out the SDK, could you share an actual snippet of of the code you are using to set the SharePoint snippet
