### ISSUE TITLE
How to use the /consumers endpoint

### ISSUE THREAD

**Issue by AngangGuo** [microsoftgraph/msgraph-beta-sdk-go#50]
I want to write a Go app to process my file in OneDrive and want to try this library.

I followed the instruction in Readme.md and here is the sample program:

```
func main() {
	cred, err := azidentity.NewDeviceCodeCredential(&azidentity.DeviceCodeCredentialOptions{
		TenantID: tenantID,
		ClientID: clientID,
		UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
			fmt.Println(message.Message)
			return nil
		},
	})

	if err != nil {
		fmt.Printf("Error creating credentials: %v\n", err)
	}

	auth, err := a.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{"Files.Read"})
	if err != nil {
		fmt.Printf("Error authentication provider: %v\n", err)
		return
	}

	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		fmt.Printf("Error creating adapter: %v\n", err)
		return
	}
	client := msgraphsdk.NewGraphServiceClient(adapter)

	result, err := client.Me().Drive().Get(nil)
	if err != nil {
		fmt.Printf("Error getting the drive: %v\n", err)
		return
	}
	fmt.Printf("Found Drive : %v\n", result.GetId())
}
```

When I run this program, I got this error message:

```
Error getting the drive: DeviceCodeCredential authentication failed
POST https://login.microsoftonline.com/f8cdef31-a31e-xxxx-93e4-5f571e91255a/oauth2/v2.0/devicecode
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_request",
  "error_description": "AADSTS9002331: Application 'faa54b57-9ed8-xxxx-91f0-f6ffe2932476'(try) is configured for use by Microsoft Account users only. Please use the /consumers endpoint to serve this request.\r\nTrace ID: de79197b-43a9-42ac-8c7c-7df660385901\r\nCorrelation ID: 11a6e4d0-78e9-40f1-b7cc-41a94bdacb45\r\nTimestamp: 2022-02-21 07:27:51Z",
  "error_codes": [
    9002331
  ],
  "timestamp": "2022-02-21 07:27:51Z",
  "trace_id": "de79197b-43a9-42ac-8c7c-7df660385901",
  "correlation_id": "11a6e4d0-78e9-40f1-b7cc-41a94bdacb45"
}
--------------------------------------------------------------------------------
```
I'm new to Microsoft Graph API and Azure. 
How can I specify the `/consumers` endpoint from the above program?
Or how can I config my app permission to make this program works?
Please advise.
Thanks

**Comment by baywet** [comment]
Hi @AngangGuo,
Thanks for trying the Go SDK and for reaching out.
Can you share what value you set for the tenantId variable please? (if it's a guid, you can obfuscate some characters) Can you try with `consumers` instead please?
Thanks!

**Comment by AngangGuo** [comment]
>>> Can you share what value you set for the `tenantId` variable please?

Here are the variables used in the program:

```
var (
	tenantID     = "f8cdef31-a31e-xxxx-93e4-5f571e91255a"
	clientID     = "faa54b57-9ed8-xxxx-91f0-f6ffe2932476"
)
```
Note: I've replace the middle part with `xxxx`. Let me know if you need more information

>>> Can you try with `consumers` instead please?

Sorry, how can I try with `consumers`

**Comment by baywet** [comment]
Replace the value for tenant is by 'consumers'

**Comment by AngangGuo** [comment]
The problem is because I selected the wrong application supported account type when registering my app.

I selected the third option `Personal Microsoft accounts only`. If I select the first or second option, the above program will proceed without the error.

<hr>

### Supported account types

**Who can use this application or access this API?**

- Accounts in any organizational directory (Any Azure AD directory - Multitenant)
- Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)
- Personal Microsoft accounts only

<hr>

The example program in the instruction is good, the problem is caused by app registration problem and my tenant account problem. 
Thanks for your help.

**Comment by baywet** [comment]
Thank you for sharing the solution with the community. I was assuming you intended to build a consumer application.

**Comment by yxzlwz** [comment]
> The problem is because I selected the wrong application supported account type when registering my app.
> 
> I selected the third option `Personal Microsoft accounts only`. If I select the first or second option, the above program will proceed without the error.
> ### Supported account types
> 
> **Who can use this application or access this API?**
> 
>     * Accounts in any organizational directory (Any Azure AD directory - Multitenant)
> 
>     * Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)
> 
>     * Personal Microsoft accounts only
> 
> 
> The example program in the instruction is good, the problem is caused by app registration problem and my tenant account problem. Thanks for your help.

I faced the same problem when I was trying to use the OneDrive API, and that's the idea. Thanks a lot.

**Comment by ubergeekseven** [comment]
cool but, how do you actually use the consumer endpoint to build an app for consumers capable of pulling in graph api data? Unreal that this does not seem to be covered anywhere.
